files:
  - source: /locales/en_US.json
    translation: /folder/%two_letters_code%/%locale_with_underscore%.json
  - source: /locales/pt-pt.json
    translation: /folder/%two_letters_code%/%locale_with_underscore%.json
