files:
  - source: /locales/en_US.json
    translation: /folder/%two_letters_code%/%original_file_name%
  - source: /locales/pt-pt.json
    translation: /folder/%two_letters_code%/%original_file_name%
